export const ACTION_TYPES = {
  SET_USERS:'SET_USERS',
  SET_PAGES:'SET_PAGES',
  SET_CURRENT_USER:'SET_CURRENT_USER',
  SET_CURRENT_PAGE:'SET_CURRENT_PAGE',
  DELETE_USER:'DELETE_USER',
  UPDATE_USER:'UPDATE_USER',
}
