export const ACTION_TYPES = {
  SET_USERS:'SET_USERS',
  SET_PAGES:'SET_PAGES',
  SET_IMAGES:'SET_IMAGES',
  SET_CURRENT_USER:'SET_CURRENT_USER',
  ADD_USER:'ADD_USER',
  DELETE_USER:'DELETE_USER',
  UPDATE_USER:'UPDATE_USER',
  CREATE_FORM_OPENED:'CREATE_FORM_OPENED',
  UPDATE_FORM_OPENED:'UPDATE_FORM_OPENED',
}
